<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Architecture.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="RepoDb.SqlServer" Version="1.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Application/Application.csproj" />
    <ProjectReference Include="../../src/Common/Common.csproj" />
    <ProjectReference Include="../../src/Crosscutting/Crosscutting.csproj" />
    <ProjectReference Include="../../src/Infrastructure/Infrastructure.csproj" />
    <ProjectReference Include="../../src/SharedKernel/SharedKernel.csproj" />
    <ProjectReference Include="../../src/Contexts/Samples/CarPreferences.Domain/CarPreferences.Domain.csproj" />
    <ProjectReference Include="../../src/Contexts/Samples/CarPreferences.Application/CarPreferences.Application.csproj" />
    <ProjectReference Include="../../src/Contexts/Samples/CarPreferences.Infrastructure/CarPreferences.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Contexts/Auth/Identity.Domain/Identity.Domain.csproj" />
    <ProjectReference Include="../../src/Contexts/Auth/Identity.Application/Identity.Application.csproj" />
    <ProjectReference Include="../../src/Contexts/Auth/Identity.Infrastructure/Identity.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Contexts/Master/Employee.Domain/Employee.Domain.csproj" />
    <ProjectReference Include="../../src/Contexts/Master/Employee.Application/Employee.Application.csproj" />
    <ProjectReference Include="../../src/Contexts/Master/Employee.Infrastructure/Employee.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Presentation/Shared/Shared.csproj" />
  </ItemGroup>

</Project>