<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Common\Common.csproj" />
    <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Crosscutting\Crosscutting.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Contexts\Samples\CarPreferences.Domain\CarPreferences.Domain.csproj" />
    <ProjectReference Include="..\..\src\Contexts\Samples\CarPreferences.Application\CarPreferences.Application.csproj" />
    <ProjectReference Include="..\..\src\Contexts\Samples\CarPreferences.Infrastructure\CarPreferences.Infrastructure.csproj" />
  </ItemGroup>

</Project>
