<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\configs\AppSettings\appsettings.Debug.json" Link="configs\appsettings.Debug.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\configs\AppSettings\appsettings.json" Link="configs\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\configs\AppSettings\appsettings.Release.json" Link="configs\appsettings.Release.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="configs\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\configs\NLog\NLog.config" Link="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="34.2.8" />
    <PackageReference Include="Syncfusion.SfInput.WPF" Version="34.2.8" />
    <PackageReference Include="Syncfusion.SfBusyIndicator.WPF" Version="34.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contexts\Department\Department.Application\Department.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Department\Department.Infrastructure\Department.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Employee\Employee.Application\Employee.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Employee\Employee.Infrastructure\Employee.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Authentication\Authentication.Application\Authentication.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Authentication\Authentication.Infrastructure\Authentication.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\IntegrationPrototype\IntegrationPrototype.Application\IntegrationPrototype.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Intrinsic.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
