<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Syncfusion.Licensing" Version="34.2.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Authentication\Authentication.Application\Authentication.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\IntegrationPrototype\IntegrationPrototype.Application\IntegrationPrototype.Application.csproj" />
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\..\Crosscutting\Crosscutting.csproj" />
  </ItemGroup>

</Project>
