<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Application\Application.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Department.Application\Department.Application.csproj" />
    <ProjectReference Include="..\Department.Domain\Department.Domain.csproj" />
  </ItemGroup>

</Project>
